<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SportsPipeline.Classifier.Orleans-8d7aa5aa-8dfb-4543-8f60-c4209ff330ae</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Orleans.Server" />
    <PackageReference Include="Microsoft.Orleans.Persistence.Redis" />
    <PackageReference Include="Orleans.Providers.MongoDB" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportsPipeline.Domain\SportsPipeline.Domain.csproj" />
    <ProjectReference Include="..\SportsPipeline.Abstractions\SportsPipeline.Abstractions.csproj" />
    <ProjectReference Include="..\SportsPipeline.Contracts\SportsPipeline.Contracts.csproj" />
    <ProjectReference Include="..\SportsPipeline.Infrastructure.Kafka\SportsPipeline.Infrastructure.Kafka.csproj" />
    <ProjectReference Include="..\SportsPipeline.Infrastructure.OpenSearch\SportsPipeline.Infrastructure.OpenSearch.csproj" />
    <ProjectReference Include="..\SportsPipeline.Infrastructure.Redis\SportsPipeline.Infrastructure.Redis.csproj" />
    <ProjectReference Include="..\SportsPipeline.Infrastructure.Mongo\SportsPipeline.Infrastructure.Mongo.csproj" />
  </ItemGroup>
</Project>
