<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <RootNamespace>SportsPipeline.Scrapper</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="System.Threading.RateLimiting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SportsPipeline.Contracts\SportsPipeline.Contracts.csproj" />
    <ProjectReference Include="..\SportsPipeline.Mapping\SportsPipeline.Mapping.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="providers.sample.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
